RESTINCL(8)
===========
:doctype: manpage


NAME
----
restincl - Enduro/X HTTP REST incoming call handler (HTTP Server, XATMI Client)


SYNOPSIS
--------
*restincl*


DESCRIPTION
-----------
This is XATMI client which accepts HTTP/HTTPS REST requests, calls the XATMI server
specified in configuration. The binary works with go routines (very cheap threads).
But the number of concurrent invocations to XATMI sub-system is limited by *workers*
initialization configuration flag. In case if all workers are busy, the incoming thread
will wait for the XATMI worker to become free.

The configuration is defined in mixed for with INI and JSON formats. The
configuration file contains keys which value can be set as multi-line JSON.
Configuration file contains *defaults* key which defines the default parameters for
the route. Then when new route is added, firstly it is initialized from defaults
and then additionally it is overridden by route it self.

Incoming HTTP REST server (XATMI client), supports multiple buffer formats and
different error handling schemes. Buffer formats can be:

. *json2ubf* - JSON Converted to UBF XATMI buffer type;

. *json* - JSON text directly set in UBF JSON buffer type;

. *text* - XATMI Typed String buffer format. Incoming text is copied to String buffer;

. *raw* - XATMI Carray buffer format; The incoming data is copied to Carray buffer type;


The error handling can be done in following ways:

. *http* - mapped HTTP error codes are being used for indicating XATMI failure codes;

. *json* - XATMI error codes are projected to JSON text root level two fields:
code and message;

. *text* - The error code is printed in output response buffer text by using format
specified in config;

. *json2ubf* - The error code is set in Enduro/X standard buffer fields and later
Converted to JSON buffer.


The operation modes of the REST interface can by:

. Synchronous - with http call XATMI services are invoked in Synchronous mode, waiting
for the sub-system answer or timeout that provides the corresponding response error
code.

. Asynchronous - invocation does the asynchronous call to XATMI service. The answer
to http rest call is return of formatted error code and message. Indicating success
or fail of asyn service invocation.

The typical *restincl* configuration looks like:

--------------------------------------------------------------------------------

[@restin]
port=8080
ip=0.0.0.0
#
# Defaults: conv=json2ubf
# async - call service in async way, if submitted ok, just reply back with ok
#
# Hmm we could use same format for definding defaults...
defaults={"errors":"http"
        ,"reqlogsvc": "GETFILE"
        ,"noreqfilersp": true
        }
      
# Service 1 
/svc1={"svc":"DATASV1", "notime":false, "conv":"json2ubf", "errors":"json", "async":false
        ,"errfmt_json_code":"\"error_code1\":%d"
        ,"errfmt_json_msg":"\"error_message1\":\"%s\""}
        
# Echo service:
/echo={"notime":false, "conv":"json2ubf", "errors":"json", "async":false, "echo":true}

--------------------------------------------------------------------------------


HTTPS mode is also supported. In this case configuration file contains ssl certificate
file and key file. The format of these files are in x509 format.

It is possible to configure per request logging files. Then the parameter *reqlogsvc*
must be set which indicates the service name which to invocate to acquire the
request logging file name.

In case if multiple REST-IN handlers are needed with different binding IP/PORTS/HTTPS
settings. it is possible to use *NDRX_CCTAG* setting (environment or in client
process monitor configuration).

Next sections will describe supported buffer formats and it's handling in the
Enduro/X.

Conversion buffer type: 'json2ubf' - JSON converted to UBF message handling
---------------------------------------------------------------------------
With 'JSON2UBF' mode, it is expected that configured web service will receive JSON
document formatted in one level, where basically data is encode in key:value
format. Array's types is supported. The array elements are loaded into UBF buffer
field occurrences. The BLOB elements are encoded as Base64 data and are loaded
into UBF buffer's BFLD_CARRAY typed fields in decoded (binary form). If target field
is not BFLD_CARRAY, then it is treated as string data and loaded into field via
conversion functions.


The JSON2UBF POST REST data of service invocation of would look like:

--------------------------------------------------------------------------------
{
	"T_CHAR_FLD":"A",
	"T_SHORT_FLD":123,
	"T_LONG_FLD":444444444,
	"T_FLOAT_FLD":1.33,
	"T_DOUBLE_FLD":4444.3333,
	"T_STRING_FLD":["HELLO", "WORLD"],
	"T_CARRAY_FLD":"SGVsbG8="
}
--------------------------------------------------------------------------------

That would be converted into following UBF buffer:

--------------------------------------------------------------------------------
T_CHAR_FLD	A
T_SHORT_FLD	123
T_LONG_FLD	444444444
T_FLOAT_FLD	1.33
T_DOUBLE_FLD	4444.3333
T_STRING_FLD	HELLO
T_STRING_FLD	WORLD
T_CARRAY_FLD	Hello
--------------------------------------------------------------------------------

When response is generated for caller, the UBF buffer coming back from Enduro/X IPC
would be in the same JSON format as in request - single level JSON document with
arrays if necessary i.e. hvae multiple occurrences for field.

The 'restincl' for incoming data does not check the MIME type, but in response
MIME type will be set to: 'text/plain'.


Conversion buffer type: 'json' - Direct JSON buffer
---------------------------------------------------
In this case JSON text is received in POST message and buffer is loaded into XATMI
buffer type 'JSON'. Buffer is sent to target service. It is expected that target
service will respond with valid JSON text back which is returned in HTTP response.
In this case too, the response type is set to 'text/plain'.

Conversion buffer type: 'text' - Arbitrary text message
-------------------------------------------------------
In this case arbitrary string is received from POST message. The string is loaded
into Enduro/X buffer type 'STRING'. And with this buffer the message is delivered
to destination service (*svc* field from route configuration). The response also
is generated as pure string, with MIME set to 'text/plain'.


Conversion buffer type: 'raw' - BLOB message
--------------------------------------------
In this case arbitrary binary (BLOB) data is received from POST message. 
The BLOB is loaded inti 'CARRAY' typed buffer and destination service is invoked
with this buffer. If service invocation is success, then the received BLOB message
from XATMI sub-system is returned to caller. In this case response will be generated
as 'application/octet-stream'.


Error handling type: 'http' - return error codes in HTTP protocol
-----------------------------------------------------------------
With this error handling method, the error codes are returned within HTTP protocol.
The error code can be mapped from XATMI subsystem to HTTP codes by using 
'errors_fmt_http_map' parameter in service or 'default' parameter block. The default
mapping which is set if 'errors_fmt_http_map' is not present, is following:

. atmi.TPMINVAL (0) =  http.StatusOK (200)
. atmi.TPEABORT (1) = http.StatusInternalServerError (500)
. atmi.TPEBADDESC (2) =  http.StatusBadRequest (400)
. atmi.TPEBLOCK (3) =  http.StatusInternalServerError (500)
. atmi.TPEINVAL (4) =  http.StatusBadRequest (400)
. atmi.TPELIMIT(5) =  http.StatusRequestEntityTooLarge (413)
. atmi.TPENOENT (6) =  http.StatusNotFound (404)
. atmi.TPEOS (7) =  http.StatusInternalServerError (500)
. atmi.TPEPERM (8) =  http.StatusUnauthorized (401)
. atmi.TPEPROTO (9) =  http.StatusBadRequest (400)
. atmi.TPESVCERR (10) =  http.StatusBadGateway (502)
. atmi.TPESVCFAIL (11) =  http.StatusInternalServerError (500)
. atmi.TPESYSTEM (12) =  http.StatusInternalServerError (500)
. atmi.TPETIME (13) =  http.StatusGatewayTimeout (504)
. atmi.TPETRAN (14) =  http.StatusInternalServerError (500)
. atmi.TPERMERR (16) =  http.StatusInternalServerError (500)
. atmi.TPEITYPE (17) =  http.StatusInternalServerError (500)
. atmi.TPEOTYPE (18) =  http.StatusInternalServerError (500)
. atmi.TPERELEASE (19) =  http.StatusInternalServerError (500)
. atmi.TPEHAZARD (20) =  http.StatusInternalServerError (500)
. atmi.TPEHEURISTIC (21) =  http.StatusInternalServerError (500)
. atmi.TPEEVENT (22) =  http.StatusInternalServerError (500)
. atmi.TPEMATCH (23) =  http.StatusInternalServerError (500)
. atmi.TPEDIAGNOSTIC (24) =  http.StatusInternalServerError (500)
. atmi.TPEMIB (25) =  http.StatusInternalServerError (500)
. Anything else (\*) = http.StatusInternalServerError (500)

Error handling type: 'json' - response code embedded JSON response message
--------------------------------------------------------------------------
This is suitable for 'json' and 'json2ubf' buffer types. On response the JSON
block is appended at then end with two fields. The fields are set with format
string *%s* for error message in 'errfmt_json_msg' parameter, for example 
*"error_message":"%s"*. The error code format is set with *%d* in 'errfmt_json_code'
parameter, for example: *"error_code":%d*. The error codes are XATMI standard defined
in xatmi.h. For example if calling JSON service and call times out, then response
will be look like:

--------------------------------------------------------------------------------

{"error_code":13,"error_message":"13:TPETIME (last error 13: ndrx_mq_receive failed: Connection timed out)"}

--------------------------------------------------------------------------------


Error handling type: 'json2ubf' - UBF format field in JSON response message
---------------------------------------------------------------------------
With this error handling mechanisms, which is suitable for 'JSON2UBF' buffer 
conversion mode, the error message is loaded into top level JSON field 'EX_IF_ECODE'
and error message is loaded into 'EX_IF_EMSG' field. This is suitable in case if
using *restout* on the other Enduor/X server to bridge the servers using HTTP/Rest
method.

Error handling type: 'text' - Free format text error code and message
---------------------------------------------------------------------
The error code and message is generated in free form text which is provided by
'errfmt_text' service parameter block field. The first parameter in format string
must be '%d' - for XATMI error, and next parameter in format string must be '%s'-
for error message. For example 'errfmt_text' could be set to *%d: %s*.


CONFIGURATION
-------------
*port* = 'PORT_NUMBER'::
Port number to listen on which http server will listen on. Mandatory option.

*ip* = 'IP_ADDRESS'::
Ip address on which http server is listening for incoming connections. Default
*0.0.0.0*.

*workers* = 'NUMBER_OF_XATMI_SESSIONS'::
Number XATMI sessions. These sessions are use for serving the incoming calls - 
i.e. doing the calls to XATMI sub-system. If the number is less than incoming calls,
the calls will be suspended while there will be no XATMI session free. Once it is
made free, then call will be served (i.e. called corresponding XATMI counterpart).
The default value for parameter is *10*.

*gencore* = 'GENERATE_CORE_FILE'::
If set to *1*, then in case of segmentation fault, the core dump will be generated
instead of Golang default signal handler which just prints some info in stderr.
The default value is *0* which means use default Golang panic handling mechanisms. 

*tls_enable* = 'ENABLE_HTTPS'::
With this setting set to *1*, HTTPS will be enabled. Default value is *0*. To complete
the HTTPS activation, configuration flags 'tls_cert_file' and 'tls_key_file' must
be set too. Otherwise program will run in HTTP mode.

*defaults* = 'SERVICE_CONFIGURATION_JSON*::
This is JSON string (can be multiline), setting the defaults for the services. It
is basically a service descriptor which is used as base configuration for services.
Once the service is being setup, firstly it uses this 'defaults' config block and
then overrides it by additional flags in service definition block. The details
within the JSON are described in bellow section *SERVICE CONFIGURATION*.

*/some/service/url* = 'SERVICE_CONFIGURATION_JSON*::
This is the same configuration as for *default*, but describes the service route.
The REST-IN process might have as many as needed the service mapping routes.

SERVICE CONFIGURATION
---------------------
*svc* = 'MAPPED_XATMI_SERVICE_NAME'::
This is the name of the target XATMI service which needs to be invoked when POST
message is received. The invocation might be synchronous, in which case caller will
wait for service to complete or receive XATMI time-out. If service completes, then
response is generated back to caller in configured format (conv parameter). If
service fails or times-out. The error is returned. Depending on error handling
mode (*errors* parameter), the data buffer can be returned too, including the 
erroneous buffer data, because XATMI services at application level errors *TPESVCFAIL*
returns the data buffer from service even the error occurred. The data is returned
with error in case of following error handling methods: *http*, *json*, *json2ubf*.

*errors* = 'ERROR_HANDLING'::
The parameter can be set to following values *http*, *json*, *json2ubf* and *text*.
See the working modes of each of the modes in above text.

*notime* = 'NO_TIMEOUT'::
Set value to *1* if service call shall be run with out XATMI sub-system tpcall()
timeout value. Default is *0*, meaning that standard timeout settings applies on
the destination service call.

*errfmt_text* = 'TEXT_BUFFER_ERROR_FORMAT_STRING'::
Format string for buffer to return in case if destination service invocation fails.
Format text will be invoked with "%d" representing the error code and then with
"%s" representing the error message. This error string is used in case if
'errors' parameter is set to *text*. The format string will be used only in case
of tpcall(3) error. If no error occurs, then service answer message is returned.
If case if asynchronous invocation is done to service ('async' param set to *1*),
the format string will be used, the status code will be returned, including 0
if *tpacall(3)* did succeed.

*errfmt_json_msg* = 'JSON_BUFFER_ERROR_FORMAT_STRING_MESSAGE'::
JSON error message field format string. Normally this would be set to JSON field 'like'
syntax. This field is used in case if 'errors' parameter is set to *json*. The
default value for the field is *"error_message":"%s"*. TODO: Usage!

*errfmt_json_code* = 'JSON_BUFFER_ERROR_FORMAT_STRING_CODE'::
JSON message field format for presenting XATMI error code occurred while doing the
service invocation. This field is together with 'errfmt_json_msg' field. The format
string for the field is '%d', meaning that it is XATMI error code. The default value
for this parameter is TODO.

*errfmt_json_onsucc* = 'ADD_JSON_ERROR_FIELDS_ON_SUCCEESS'::
.

*async* = 'DO_ASYNC_SERVICE_INVOCATION*::
.

*asyncecho* = 'ECHO_BACK_BUFFER_DURING_ASYNC_INVOCATION'::
.

*conv* = 'BUFFER_CONVERTION_TYPE'::
.

*reqlogsvc* = 'REQUEST_LOGGING_SERVICE'::
.

*errors_fmt_http_map* = 'HTTP_ERROR_CODES_MAPPING'::
.

*noreqfilersp* = 'DO_NOT_SEND_REQUEST_FILENAME_BACK_TO_CALLER'::
.

*echo* = 'ECHO_MODE'::
.


EXIT STATUS
-----------
*0*::
Success

*1*::
Failure

BUGS
----
Report bugs to madars.vitolins@gmail.com

SEE ALSO
--------
*restoutsv(8)*

AUTHOR
------
Enduro/X is created by Madars Vitolins.


COPYING
-------
(C) Mavimax SIA

