RESTINCL(8)
===========
:doctype: manpage


NAME
----
restincl - EnduroX HTTP REST incoming call handler (HTTP Server, XATMI Client)


SYNOPSIS
--------
*restincl*


DESCRIPTION
-----------
This is XATMI client which accepts HTTP/HTTPS REST requests, calls the XATMI server
specified in configuration. The binary works with go routines (very cheap threads).
But the number of concurrent invocations to XATMI sub-system is limited by *workers*
initialization configuration flag. In case if all workers are busy, the incoming thread
will wait for the XATMI worker to become free.

The configuration is defined in mixed for with INI and JSON formats. The
configuration file contains keys which value can be set as multi-line JSON.
Configuration file contains *defaults* key which defines the default parameters for
the route. Then when new route is added, firstly it is initialized from defaults
and then additionally it is overridden by route it self.

Incoming HTTP REST server (XATMI client), supports multiple buffer formats and
different error handling schemes. Buffer formats can be:

. *json2ubf* - JSON Converted to UBF XATMI buffer type;

. *json* - JSON text directly set in UBF JSON buffer type;

. *text* - XATMI Typed String buffer format. Incoming text is copied to String buffer;

. *raw* - XATMI Carray buffer format; The incoming data is copied to Carray buffer type;


The error handling can be done in following ways:

. *http* - mapped HTTP error codes are being used for indicating XATMI failure codes;

. *json* - XATMI error codes are projected to JSON text root level two fields:
code and message;

. *text* - The error code is printed in output response buffer text by using format
specified in config;

. *json2ubf* - The error code is set in Enduro/X standard buffer fields and later
Converted to JSON buffer.


The operation modes of the REST interface can by:

. Synchronous - with http call XATMI services are invoked in Synchronous mode, waiting
for the sub-system answer or timeout that provides the corresponding response error
code.

. Asynchronous - invocation does the asynchronous call to XATMI service. The answer
to http rest call is return of formatted error code and message. Indicating success
or fail of asyn service invocation.

The typical *restincl* configuration looks like:

--------------------------------------------------------------------------------

[RESTIN]
port=8080
ip=0.0.0.0
#
# Defaults: conv=json2ubf
# async - call service in async way, if submitted ok, just reply back with ok
#
# Hmm we could use same format for definding defaults...
defaults={"errors":"http"
        ,"reqlogsvc": "GETFILE"
        ,"noreqfilersp": true
        }
      
# Service 1 
/svc1={"svc":"DATASV1", "notime":false, "conv":"json2ubf", "errors":"json", "async":false
        ,"errfmt_json_code":"\"error_code1\":%d"
        ,"errfmt_json_msg":"\"error_message1\":\"%s\""}
        
# Echo service:
/echo={"notime":false, "conv":"json2ubf", "errors":"json", "async":false, "echo":true}

--------------------------------------------------------------------------------


HTTPS mode is also supported. In this case configuration file contains ssl certificate
file and key file. The format of these files are in x509 format.

It is possible to configure per request logging files. Then the parameter *reqlogsvc*
must be set which indicates the service name which to invocate to acquire the
request logging file name.

In case if multiple REST-IN handlers are needed with different binding IP/PORTS/HTTPS
settings. it is possible to use *NDRX_CCTAG* setting (environment or in client
process monitor configuration).

The JSON2UBF invocation of the service would look like:

--------------------------------------------------------------------------------

...

--------------------------------------------------------------------------------

And the response message would look like:

--------------------------------------------------------------------------------

...

--------------------------------------------------------------------------------




CONFIGURATION
-------------
*port* = 'PORT_NUMBER'::
Port number to listen on which http server will listen on. Mandatory option.

*ip* = 'IP_ADDRESS'::
Ip address on which http server is listening for incoming connections. Default
*0.0.0.0*.

*workers* = 'NUMBER_OF_XATMI_SESSIONS'::
Number XATMI sessions. These sessions are use for serving the incoming calls - 
i.e. doing the calls to XATMI sub-system. If the number is less than incoming calls,
the calls will be suspended while there will be no XATMI session free. Once it is
made free, then call will be served (i.e. called corresponding XATMI counterpart).
The default value for parameter is *10*.

*gencore* = 'GENERATE_CORE_FILE'::
If set to *1*, then in case of segmentation fault, the core dump will be generated
instead of Golang default signal handler which just prints some info in stderr.
The default value is *0* which means use default Golang panic handling mechanisms. 

*tls_enable* = 'ENABLE_HTTPS'::
With this setting set to *1*, HTTPS will be enabled. Default value is *0*. To complete
the HTTPS activation, configuration flags *tls_cert_file* and *tls_key_file* must
be set too. Otherwise program will run in HTTP mode.

*defaults* = 'SERVICE_CONFIGURATION_JSON*::
This is JSON string (can be multiline), setting the defaults for the services. It
is basically a service descriptor which is used as base configuration for services.
Once the service is being setup, firstly it uses this *defaults* config block and
then overrides it by additional flags in service definition block. The details
within the JSON are described in bellow section "SERVICE CONFIGURATION.

*/some/service/url* = 'SERVICE_CONFIGURATION_JSON*::
This is the same configuration as for *default*, but describes the service route.
The REST-IN process might have as many as needed the service mapping routes.

SERVICE CONFIGURATION
---------------------
*svc* = 'MAPPED_XATMI_SERVICE_NAME'::
.

*errors* = 'ERROR_HANDLING'::
.

*notime* = 'NO_TIMEOUT'::
.

*errfmt_text* = 'TEXT_BUFFER_ERROR_FORMAT_STRING'::
.

*errfmt_json_msg* = 'JSON_BUFFER_ERROR_FORMAT_STRING_MESSAGE'::
.

*errfmt_json_code* = 'JSON_BUFFER_ERROR_FORMAT_STRING_CODE'::
.

*errfmt_json_onsucc* = 'ADD_JSON_ERROR_FIELDS_ON_SUCCEESS'::
.

*async* = 'DO_ASYNC_SERVICE_INVOCATION*::
.

*asyncecho* = 'ECHO_BACK_BUFFER_DURING_ASYNC_INVOCATION'::
.

*conv* = 'BUFFER_CONVERTION_TYPE'::
.

*reqlogsvc* = 'REQUEST_LOGGING_SERVICE'::
.

*errors_fmt_http_map* = 'HTTP_ERROR_CODES_MAPPING'::
.

*noreqfilersp* = 'DO_NOT_SEND_REQUEST_FILENAME_BACK_TO_CALLER'::
.

*echo* = 'ECHO_MODE'::
.


EXIT STATUS
-----------
*0*::
Success

*1*::
Failure

BUGS
----
Report bugs to madars.vitolins@gmail.com

SEE ALSO
--------
*xadmin(8)*

AUTHOR
------
Enduro/X is created by Madars Vitolins.


COPYING
-------
(C) Madars Vitolins

