TCPGATESV(8)
============
:doctype: manpage


NAME
----
tcpgatesv - Enduro/X user programmable tpc gateway (client/server roles, XATMI server).

SYNOPSIS
--------
*tcpgatesv*

DESCRIPTION
-----------
Use programmable tcp gateway. The server gives for programmer abstraction over the tcp
sockets. This module gives programmer abstraction over of the socket to the next level - 
XATMI services. By using tpcgateway for programmer to send network message, it is sufficient
for dong the XATMI service invocation with specific UBF buffer, containing the message to
be sent to network. The network address now is abstracted to XATMI service name. All other
details technical details of socket operations are covered by *tcpgatesv*.

The getaway is able to handle multiple simultaneous connections. The connections are identified
by connection id, which cosists of two parts - simple connection id (started from Nr. 1) and
by compiled connection id, where part of the number contains the actual timestamp when
connection is established.

Getaway can operate with persistent connections, so that tcpgatesv opens the number of
connections, and callers (from both ends XATMI and network) can do the invocations synchronously
or asynchronously. In async mode it is still possible to simulate synchronous service invocations,
that is done in case if 'corr_svc' parameter is set. This parameter indicates which
service which to invoke for sending incoming message for parsing. The correlation service
can parse the message, and respond with parsed correlation id (in 'EX_NETCORR').
Then by this given correlation ID, the gateway server will lookup any XATMI callers
in progress, if found, then they are replied with buffer coming from 'corr_svc'.
If correlation id is not parsed or no waiters in progress, then 'incoming_svc' is
called with given incoming/'corr_svc' response buffer.

Geteway can operate in one request-new connection mode from both ends, it can accept the request
from network (in this case we must be passive - wait for conn). And it can create new connection
when doing the XATMI request to network. After receiving response from network or getting timeout,
the connection is closed.

Module allows the system to track the status of the connections. When gateway boots, it
sends disconnected status to target connection tracking server ('status_svc' service in ini config).
When connection is established either in active or passive mode, the status of connection
is sent to status service.

It is possible to configure gateway to send keep-a-live messages. The keep a live message
is zero length. Thus can be safely ignored by network target device. The same as *tcpgatesv*
does.

Tcpgateway uses different message framing algorithms, to avoid partially read messages
from network, which can occur if message size is larger than message transfer unit (MTU).
Framing mode is controlled by 'framing' parameter. Following options are supported:

. a+ - ASCII formatted string message length

. A+ - ASCII formatted string with message length, including the length bytes

. ll+ - little endian byte order (from one to 8 bytes)

. LL+ - little endian byte order (from one to 8 bytes), message length includes length bytes by it self

. bb+ - big endian byte order (from one to 8 bytes)

. BB+ - big endian byte order (from one to 8 bytes), message length includes length bytes

. d - Message end delimiter byte

. D - Message start and end delimiter byte

Note that if even bytes are used for connection length indication, it is possible,
to swap them in half by using 'framing_half_swap' parameter. This is suitable
for connecting to VISA payment network, which uses little endian 4 bytes, which
are swapped in big endian order by two halves.

The administrator can configure *tcpgatesv* for different roles:

. Tcp socket server - listener (passive mode)

. Tcp socket client - connects  (active mode)

The tcpgateway can operate in different logical modes (type param):

. 'A' - Active mode, our side initiate connection (tcp client)

. 'P' - Passive mode, our side does listen on socket (tcp server)

The next sections will show samples for different framing methods, including
settings of 'framing' and 'framing_half_swap'. The test message that will be
demonstrated in bellow framing modes are: 'AHELLO WORLD\\10\\11\\12\\13TEST\\ff',
the total number of bytes: 21.

Mode: 'framing' = aa, framing_half_swap=0
-----------------------------------------

--------------------------------------------------------------------------------
  0000  32 31 48 45 4c 4c 4f 20 57 4f 52 4c 44 00 10 11  21HELLO WORLD...
  0010  12 13 54 45 53 54 ff                             ..TEST.
--------------------------------------------------------------------------------

Mode: 'framing' = AAAA, framing_half_swap=0
-------------------------------------------

--------------------------------------------------------------------------------
  0000  30 30 32 35 48 45 4c 4c 4f 20 57 4f 52 4c 44 00  0025HELLO WORLD.
  0010  10 11 12 13 54 45 53 54 ff                       ....TEST.
--------------------------------------------------------------------------------

Mode: 'framing' = llll, framing_half_swap=1
-------------------------------------------

--------------------------------------------------------------------------------
  0000  00 15 00 00 48 45 4c 4c 4f 20 57 4f 52 4c 44 00  ....HELLO WORLD.
  0010  10 11 12 13 54 45 53 54 ff                       ....TEST.
--------------------------------------------------------------------------------

Mode: 'framing' = LLLLLL, framing_half_swap=0
---------------------------------------------

--------------------------------------------------------------------------------
  0000  00 00 00 00 00 1b 48 45 4c 4c 4f 20 57 4f 52 4c  ......HELLO WORL
  0010  44 00 10 11 12 13 54 45 53 54 ff                 D.....TEST.
--------------------------------------------------------------------------------

Mode: 'framing' = bbbb, framing_half_swap=0
-------------------------------------------

--------------------------------------------------------------------------------
  0000  15 00 00 00 48 45 4c 4c 4f 20 57 4f 52 4c 44 00  ....HELLO WORLD.
  0010  10 11 12 13 54 45 53 54 ff                       ....TEST.
--------------------------------------------------------------------------------

Mode: 'framing' = BBBBBBBB, framing_half_swap=1
-----------------------------------------------

--------------------------------------------------------------------------------
  0000  00 00 00 00 1d 00 00 00 48 45 4c 4c 4f 20 57 4f  ........HELLO WO
  0010  52 4c 44 00 10 11 12 13 54 45 53 54 ff           RLD.....TEST.
--------------------------------------------------------------------------------

Mode: 'framing' = d, framing_half_swap=N/A
------------------------------------------
Using default message delimiter 0x03 ('delim_stop').

--------------------------------------------------------------------------------
  0000  48 45 4c 4c 4f 20 57 4f 52 4c 44 00 10 11 12 13  HELLO WORLD.....
  0010  54 45 53 54 ff 03                                TEST..
--------------------------------------------------------------------------------

Mode: 'framing' = D, framing_half_swap=N/A
------------------------------------------
Using default message marker 'delim_start'=0x02 and default message end marker
'delim_stop'=*0x03*.

--------------------------------------------------------------------------------
  0000  02 48 45 4c 4c 4f 20 57 4f 52 4c 44 00 10 11 12  .HELLO WORLD....
  0010  13 54 45 53 54 ff 03                             .TEST..
--------------------------------------------------------------------------------


SERVICE API INTERFACE
---------------------

TCP Gateway is programmed by using UBF buffers. Buffers contains specific fields
including CARRAY (BLOB) message that needs to be delivered or is received from
network.

In case of sending data to network standard *tpcall(3)* or *tpacall(3)* are used.
The target service of invocation is configured in *gateway* parameter, that is
advertised by *tpcgatewsv*. 

When message is received from network, with incoming data, the 'corr_svc' will be
invoked if configured. Finally message is delivered to 'incoming_svc', the invocation
by tcpgatesv will be done synchronously or asynchronously depending on configuration
parameters and message specification.

*Sending message to network - request*

To send message to network in use following UBF buffer (tpcall(3)):

'EX_NETDATA' - The BLOB/CARRAY data to delivery to target connection

'EX_NETCONNID' - connection id either compiled or simple. The compiled connection
id can be used when generating response back to network. The connection id is
composed of 64bit integer, where first 24 bits are connection id, and oldest 40bits
are set to UTC epoch milliseconds since start of 1970. The compiled it can be used
for doing reply to exact connection.

'EX_NETCORR' - Optional Correlator string, used for synchronous connections.

*Response from gateway service*

'EX_NERROR_CODE' - Error code, can be one of followings:

*atmi.NEMANDATORY (6)* - Mandatory field is missing ('EX_NETDATA')

*atmi.NETOUT (8)* - timeout waiting on reply

*atmi.NENOCONN (9)* - Connection not found by 'EX_NETCONNID' or no connection established.

*atmi.NELIMIT (10)* - Connection count limit reached

'EX_NERROR_MSG' - Corresponding error message.


*A. tpreturn(3) buffer to async service reply - example*

Request/reply example (from client perspective - in this example server process
does change the data bytes doing +1 over the data starting from position 5):

--------------------------------------------------------------------------------
$ ud < test.ud
SENT pkt(1) is :
EX_NETCONNID	1
EX_NETCORR	AELL
EX_NETDATA	AELLO WORLD\00\10\11\12\13TEST\ff

RTN pkt(1) is :
EX_NERROR_CODE	0
EX_NETCONNID	6481138401960525826
EX_NERROR_MSG	SUCCEED
EX_NETGATEWAY	TCP_P_ASYNC_P
EX_NETCORR	AELL
EX_NETDATA	AELLP!XPSME\01\11\12\13\14UFTU\00
--------------------------------------------------------------------------------


Incoming request at correlation service (other end reads network and sends data to
('corr_svc'), at the destination with no reply waiter, it will just invoke the
incoming service (see after this dump).

--------------------------------------------------------------------------------
EX_NETCONNID    6481138401943748609
EX_NETGATEWAY   TCP_P_ASYNC_A
EX_NETDATA      AELLO WORLD\00\10\11\12\13TEST\ff
--------------------------------------------------------------------------------

Incoming request at server ('incoming_svc'):

--------------------------------------------------------------------------------
EX_NETCONNID    6481138401943748609
EX_NETGATEWAY   TCP_P_ASYNC_A
EX_NETCORR      AELL
EX_NETDATA      AELLO WORLD\00\10\11\12\13TEST\ff
--------------------------------------------------------------------------------

Note that when message is received back from other host, it is sent for 
correlation service so that we can match the response. For this particular case
the invocation did look like:

--------------------------------------------------------------------------------
N:NDRX:5:26407:7f21c98357c0:000:20170131:010926331:_tplog.c:0099:CORSVC: Incoming request:
EX_NETCONNID    6481138401960525826
EX_NETGATEWAY   TCP_P_ASYNC_P
EX_NETDATA      AELLP!XPSME\01\11\12\13\14UFTU\00
t:USER:4:26407:7f21c98357c0:000:20170131:010926331:estsv.go:0081:Extracted correlator: [AELL]
N:NDRX:5:26407:7f21c98357c0:000:20170131:010926331:_tplog.c:0099:Reply buffer afrer correl
EX_NETCONNID    6481138401960525826
EX_NETGATEWAY   TCP_P_ASYNC_P
EX_NETCORR      AELL
EX_NETDATA      AELLP!XPSME\01\11\12\13\14UFTU\00
--------------------------------------------------------------------------------


*C. Example connection status buffer*

The connection 2 is disconnected.

--------------------------------------------------------------------------------
EX_NETCONNID    2
EX_NETGATEWAY   TCP_P_SYNC_A
EX_NETFLAGS     D
--------------------------------------------------------------------------------



CONFIGURATION
-------------

The configuration is written in CCONFIG ini file. The section for 
tcp gateway is *[@tcpgate/CCTAG]*. The *CCTAG* is optional. Following
parameters are available for tcp gateway:

*gencore = 'GENERATE_OS_CORE_DUMPS'::
If set to *1*, for signals 6 (abort), 11 (segmentation fault) default
Operating System handlers will be restored instead of go handlers. This
can be suitable when debugging cgo code.
Default is *0*.

*workers_out = 'NUMBER_OF_XATMI_SESSIONS_FOR_OUTGOING_MESSAGES'::
Number of worker sessions for dispatching message to network on doing reply back
to XATMI service caller. This basically is how many go threads will process the
incoming requests. If system is short of the threads, the main XATMI thread waiting
for incoming messages, will be suspended on waiting the free worker.
In case of 'req_reply' mode *3* (XATMI service sends to network by opening new 
connection and then closing), the 'workers_out' must be bigger or equal number
to 'max_connections'. The recommendation is to use 'max_connections' = 'workers_out'\*2
for this scenario.
Default is *5*.

*workers_in = 'NUMBER_OF_XATMI_SESSIONS_FOR_INCOMING_MESSAGES'::
Number of XATMI and go thread workers processing the incoming messages. The pool
of worker is used in case when connection receives data from network. The workers
are used for invocation of 'incoming_svc'.
Default is *5*.

*gateway* = 'TCP_GATEWAY_SERVICE_NAME'::
Gateway service name. This is service name which is advertised by the *tcpgatesv*
for accessing the outgoing message facility.
Default is *TCPGATE*.

*framing* = 'FRAMING_MODE'::
Framing mode code. This tells in what format message length is encoded.
Described above. Shortly:

'l+' - little endian byte order, does not include length of it self

'L+' - little endian byte order, include length of it self

'b+' - big endian byte order, does not include length of it self

'B+' - big endian byte order, include length of it self

'a+' - ASCII text byte order, does not include length by it self

'A+' - ASCII text byte order, does include length by it self

'd' - Use message stop indicator

'D' - Use message start & stop indicators

*framing_half_swap* = 'SWAP_FRAMING_BYTES::
.

*max_msg_len* = 'MAX_MESSAGE_LENGTH::
. TODO: Does it include len bytes?

*delim_start* = 'MESSAGE_START_DELIMITER::
.

*delim_stop* = 'MESSAGE_STOP_DELIMITER::
.

*type* = 'ACTIVE_PASSIVE_MODE'::
.

*ip* = 'IP_ADDRESS'::
.

*port* = 'TPC_PORT_NUMBER'::
.

*incoming_svc* = 'INCOMING_XATMI_SERVICE'::
.

*periodic_zero_msg* = 'PERIODIC_ZERO'::
.

*status_svc* = 'STATUS_SERVICE_NAME'::
.

*max_connections* = 'MAX_NR_OF_CONNECTIONS'::
.

*req_reply* = 'REQUEST_MODE'::
.

*req_reply_timeout* = 'REQUEST_TIMEOUT'::
.

*scan_time* = 'SCAN_TIME'::
.

*conn_wait_time* = 'CONNECTION_WAIT_TIME'::
.

*corr_svc* = 'CORRELATION_SERVICE'::
.

*debug* = 'DEBUG_STRING'::
.


EXIT STATUS
-----------
*0*::
Success

*1*::
Failure

EXAMPLE

To see the usage different usage settings, see *tests/02_tcpgatesv/runtime/conf/tcpgate.ini'*.

BUGS
----
Report bugs to madars.vitolins@gmail.com

SEE ALSO
--------
*restincl(8)* *restoutsv(8)*.

AUTHOR
------
Enduro/X is created by Madars Vitolins.


COPYING
-------
(C) Mavimax SIA

